# Generated by Django 5.0.1 on 2025-10-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiktok_events', '0003_livesession_liveevent_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('name', models.CharField(help_text='Nombre descriptivo del servicio', max_length=255)),
                ('slug', models.SlugField(help_text='Identificador único del servicio', max_length=100, unique=True)),
                ('service_class', models.CharField(help_text='Ruta completa de la clase Python (ej: apps.obs_overlay.services.OBSOverlayService)', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Descripción del servicio', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si el servicio está activo')),
                ('max_queue_size', models.IntegerField(default=100, help_text='Tamaño máximo de la cola de eventos')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('discarded', 'Discarded')], db_index=True, default='pending', help_text='Estado del evento en la cola', max_length=20)),
                ('priority', models.IntegerField(help_text='Prioridad del evento (copiada de la configuración)')),
                ('is_async', models.BooleanField(help_text='Si debe procesarse async (copiada de la configuración)')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Momento en que se procesó el evento', null=True)),
                ('live_event', models.ForeignKey(help_text='Evento de TikTok a procesar', on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='tiktok_events.liveevent')),
                ('session', models.ForeignKey(blank=True, help_text='Sesión a la que pertenece el evento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='tiktok_events.livesession')),
                ('service', models.ForeignKey(help_text='Servicio que procesará este evento', on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='queue_system.service')),
            ],
            options={
                'verbose_name': 'Event Queue Item',
                'verbose_name_plural': 'Event Queue',
                'db_table': 'event_queue',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['service', 'status', '-priority', 'created_at'], name='event_queue_service_02a765_idx'), models.Index(fields=['service', 'status'], name='event_queue_service_24531a_idx'), models.Index(fields=['live_event'], name='event_queue_live_ev_7598c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('event_type', models.CharField(choices=[('CommentEvent', 'Comment Event'), ('GiftEvent', 'Gift Event'), ('LikeEvent', 'Like Event'), ('ShareEvent', 'Share Event'), ('FollowEvent', 'Follow Event'), ('JoinEvent', 'Join Event'), ('SubscribeEvent', 'Subscribe Event')], db_index=True, help_text='Tipo de evento que se procesará', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Si este tipo de evento está habilitado para procesarse')),
                ('priority', models.IntegerField(default=5, help_text='Prioridad del evento (1-10, donde 10 es máxima prioridad)')),
                ('is_async', models.BooleanField(default=False, help_text='Si este tipo de evento puede procesarse en paralelo (async) o debe esperar (sync)')),
                ('is_discardable', models.BooleanField(default=True, help_text='Si este evento puede descartarse cuando la cola está llena')),
                ('service', models.ForeignKey(help_text='Servicio al que pertenece esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='event_configs', to='queue_system.service')),
            ],
            options={
                'verbose_name': 'Service Event Configuration',
                'verbose_name_plural': 'Service Event Configurations',
                'db_table': 'service_event_configs',
                'ordering': ['-priority', 'event_type'],
                'indexes': [models.Index(fields=['service', 'event_type', 'is_enabled'], name='service_eve_service_0c3c54_idx')],
                'unique_together': {('service', 'event_type')},
            },
        ),
    ]
