# Generated by Django 5.0.1 on 2025-10-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceeventconfig',
            name='is_stackable',
            field=models.BooleanField(default=True, help_text='Si se procesa cada regalo de la racha (True) o solo al finalizar la racha (False)'),
        ),
    ]
