# Generated by Django 5.1.3 on 2026-04-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0002_serviceeventconfig_is_stackable'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='obs_scene_name',
            field=models.CharField(blank=True, help_text='Nombre de la escena en OBS asociada a este servicio', max_length=255, null=True),
        ),
    ]
