# Generated by Django 5.0.1 on 2025-10-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiktok_events', '0003_livesession_liveevent_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('username', models.CharField(db_index=True, help_text='Username del usuario en TikTok', max_length=255)),
                ('total_gifts', models.IntegerField(default=0, help_text='Total de regalos validos enviados (incluyendo rachas)')),
                ('credits_used', models.IntegerField(default=0, help_text='Creditos ya utilizados')),
                ('last_gift_at', models.DateTimeField(blank=True, help_text='Ultima vez que envio un regalo valido', null=True)),
                ('last_request_at', models.DateTimeField(blank=True, help_text='Ultima vez que pidio una cancion', null=True)),
                ('session', models.ForeignKey(help_text='Sesion del live', on_delete=django.db.models.deletion.CASCADE, related_name='music_credits', to='tiktok_events.livesession')),
            ],
            options={
                'verbose_name': 'Music Credit',
                'verbose_name_plural': 'Music Credits',
                'db_table': 'music_credits',
                'ordering': ['-total_gifts'],
                'indexes': [models.Index(fields=['session', 'username'], name='music_credi_session_170b74_idx'), models.Index(fields=['session', '-total_gifts'], name='music_credi_session_2cd2e5_idx')],
                'unique_together': {('session', 'username')},
            },
        ),
        migrations.CreateModel(
            name='MusicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('username', models.CharField(db_index=True, help_text='Username que solicito la cancion', max_length=255)),
                ('query', models.CharField(help_text='Termino de busqueda usado', max_length=500)),
                ('youtube_url', models.URLField(help_text='URL del video de YouTube', max_length=500)),
                ('youtube_id', models.CharField(help_text='ID del video de YouTube', max_length=50)),
                ('title', models.CharField(help_text='Titulo del video', max_length=500)),
                ('duration', models.IntegerField(help_text='Duracion en segundos')),
                ('file_path', models.CharField(help_text='Ruta del archivo de audio descargado', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Cuando empezo a reproducirse')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Cuando termino la reproduccion', null=True)),
                ('was_interrupted', models.BooleanField(default=False, help_text='Si fue interrumpida por otra cancion')),
                ('session', models.ForeignKey(help_text='Sesion del live', on_delete=django.db.models.deletion.CASCADE, related_name='music_history', to='tiktok_events.livesession')),
            ],
            options={
                'verbose_name': 'Music History',
                'verbose_name_plural': 'Music History',
                'db_table': 'music_history',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session', '-started_at'], name='music_histo_session_355ce3_idx'), models.Index(fields=['username', '-started_at'], name='music_histo_usernam_7f5843_idx')],
            },
        ),
    ]
