# Generated by Django 4.2.7 on 2025-10-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('meta_key', models.CharField(db_index=True, help_text='Clave de configuración única', max_length=255, unique=True)),
                ('meta_value', models.TextField(help_text='Valor de la configuración (puede ser JSON, texto, etc.)')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'app_config',
                'ordering': ['meta_key'],
            },
        ),
    ]
