# Generated by Django 4.2.7 on 2025-10-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='Tipo de evento (CommentEvent, GiftEvent, etc.)', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Momento del evento')),
                ('room_id', models.BigIntegerField(db_index=True, help_text='ID de la sala/live')),
                ('streamer_unique_id', models.CharField(db_index=True, help_text='Username del streamer', max_length=255)),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, help_text='TikTok user ID', null=True)),
                ('user_unique_id', models.CharField(blank=True, db_index=True, help_text='Username del usuario', max_length=255, null=True)),
                ('user_nickname', models.CharField(blank=True, help_text='Nickname del usuario', max_length=255, null=True)),
                ('is_streaking', models.BooleanField(db_index=True, default=False, help_text='Si el evento está en racha activa')),
                ('streak_id', models.CharField(blank=True, db_index=True, help_text='ID único de la racha', max_length=255, null=True)),
                ('streak_status', models.CharField(blank=True, choices=[('start', 'Start'), ('continue', 'Continue'), ('end', 'End')], help_text='Estado de la racha: start, continue, end', max_length=10, null=True)),
                ('event_data', models.JSONField(help_text='Toda la información específica del evento en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se guardó en la BD')),
            ],
            options={
                'verbose_name': 'Live Event',
                'verbose_name_plural': 'Live Events',
                'db_table': 'live_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['room_id', 'timestamp'], name='live_events_room_id_600a16_idx'), models.Index(fields=['user_id', 'is_streaking', 'timestamp'], name='live_events_user_id_ea2901_idx'), models.Index(fields=['event_type', 'room_id'], name='live_events_event_t_4fe77b_idx')],
            },
        ),
    ]
