# Generated by Django 4.2.7 on 2025-10-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),
        ),
    ]
