# Generated by Django 5.0.1 on 2025-10-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_events', '0002_liveevent_updated_at_alter_liveevent_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('name', models.CharField(blank=True, help_text='Nombre opcional de la sesión', max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Inicio de la sesión')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, help_text='Fin de la sesión', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted')], db_index=True, default='active', help_text='Estado de la sesión', max_length=20)),
                ('room_id', models.BigIntegerField(db_index=True, help_text='ID de la sala/live monitoreada')),
                ('streamer_unique_id', models.CharField(db_index=True, help_text='Username del streamer', max_length=255)),
                ('total_events', models.IntegerField(default=0, help_text='Total de eventos capturados')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre esta sesión', null=True)),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'db_table': 'live_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['room_id', 'started_at'], name='live_sessio_room_id_a6061d_idx'), models.Index(fields=['status', 'started_at'], name='live_sessio_status_226cd9_idx')],
            },
        ),
        migrations.AddField(
            model_name='liveevent',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Sesión a la que pertenece este evento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tiktok_events.livesession'),
        ),
        migrations.AddIndex(
            model_name='liveevent',
            index=models.Index(fields=['session', 'timestamp'], name='live_events_session_3f0ebc_idx'),
        ),
    ]
