# Generated by Django 5.0.1 on 2025-10-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('music', 'Música de fondo'), ('voice', 'Voz/Efectos')], max_length=20, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('playing', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio Actual',
                'verbose_name_plural': 'Audios Actuales',
            },
        ),
    ]
